######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 8 08:39:43 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += constant.h mydialog.h chromosome.h genetic.h
SOURCES += constant.cpp mydialog.cpp chromosome.cpp genetic.cpp main.cpp
RESOURCES += application.qrc
